[build]
  base = "public"  # Indica que o diretório 'public' é o diretório base para a construção
  publish = "public"  # Indica que o diretório 'public' é o diretório a ser publicado

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
