name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug info
        run: |
          ls -l
          cat .cpanel.yml

      - name: Deploy to cPanel
        run: |
          cp .cpanel.yml $HOME/.cpanel.yml
          curl -s -k -o deploy.sh https://repo.cpanel.net/cpanelsync/DEPLOY
          chmod +x deploy.sh
          ./deploy.sh --force


